### PR TITLE
Update ember

### PR DESCRIPTION
**Pull request by anthony-mangano-argus**
Hi, 
I've updated your ember addons. To make it run clean with Ember 3.4

I've fixed some test. But i have some difficulties to fix the last one:
not ok 7 Chrome 69.0 - [24 ms] - integration/query-has-many: Querying has-many relationship multiple times doesn't clear belongs-to-sticky association
    ---
        actual: >
            null
        expected: >
            5
        stack: >
                at http://localhost:7357/assets/tests.js:4685:18
                at Class._emberMetal.Mixin.create._Mixin$create.forEach (http://localhost:7357/assets/vendor.js:48917:16)
                at http://localhost:7357/assets/tests.js:4681:19
                at tryCatcher (http://localhost:7357/assets/vendor.js:59436:21)
                at invokeCallback (http://localhost:7357/assets/vendor.js:59608:33)
                at publish (http://localhost:7357/assets/vendor.js:59594:9)
        message: >
            belongs-to association sticky after multiple has-many queries
        negative: >
            false

This test is about the belongs-to-sticky association.

### CODE REVIEW

**Comment by jboler** [comment]
@anthony-mangano-argus The failing test has been fixed on @kohactive's branch by using async tests:

https://github.com/kohactive/ember-data-has-many-query/blob/master/tests/integration/query-has-many-test.js#L68

It would be great to get this PR merged!

**Comment by john-griffin** [comment]
Yeah this would be great to get merged. It's required to upgrade to latest ember versions.

**Comment by alexdiliberto** [comment]
Noting that this PR also addresses the following `Ember.copy` deprecation [`ember-runtime.deprecate-copy-copyable`](https://github.com/emberjs/rfcs/issues/315)

**Comment by mdehoog** [comment]
Thank you for doing this! #36 was just merged which updates to Ember 3.6.

**Pull request closed without merging**
